server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - RemoveResponseHeader=Access-Control-Allow-Origin
        - RemoveResponseHeader=Access-Control-Allow-Credentials
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: booking-service-booking
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
        - id: booking-service-client
          uri: lb://booking-service
          predicates:
            - Path=/api/client/**
        - id: frequencydiscount-service
          uri: lb://frequencydiscount-service
          predicates:
            - Path=/api/frequencydiscount/**
        - id: groupgiscount-service
          uri: lb://groupdiscount-service
          predicates:
            - Path=/api/groupdiscount/**
        - id: incomingreport-service
          uri: lb://incomingreport-service
          predicates:
            - Path=/api/report/**
        - id: specialdays-service
          uri: lb://specialdays-service
          predicates:
            - Path=/api/specialdays/**
        - id: track-service
          uri: lb://track-service
          predicates:
            - Path=/api/track/**
        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**