
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frequencydiscount-service-deployment
  labels:
    app: frequencydiscount-service-deployment
spec:
  selector:
    matchLabels:
      app: frequencydiscount-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frequencydiscount-service-deployment
    spec:
      containers:
        - name: frequencydiscount-service
          image: gabrielcq/frequencydiscount-service
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_FREQUENCYDISCOUNT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_FREQUENCYDISCOUNT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_FREQUENCYDISCOUNT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_FREQUENCYDISCOUNT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_FREQUENCYDISCOUNT