apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_BOOKING: cG9zdGdyZXM=
  DB_PASSWORD_BOOKING: MTIzNA==

  DB_USER_FREQUENCYDISCOUNT: cG9zdGdyZXM=
  DB_PASSWORD_FREQUENCYDISCOUNT: MTIzNA==

  DB_USER_GROUPDISCOUNT: cG9zdGdyZXM=
  DB_PASSWORD_GROUPDISCOUNT: MTIzNA==

  DB_USER_INCOMINGREPORT: cG9zdGdyZXM=
  DB_PASSWORD_INCOMINGREPORT: MTIzNA==

  DB_USER_PRICING: cG9zdGdyZXM=
  DB_PASSWORD_PRICING: MTIzNA==

  DB_USER_SPECIALDAYS: cG9zdGdyZXM=
  DB_PASSWORD_SPECIALDAYS: MTIzNA==

  DB_USER_TRACK: cG9zdGdyZXM=
  DB_PASSWORD_TRACK: MTIzNA==