apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialdays-service-deployment
  labels:
    app: specialdays-service-deployment
spec:
  selector:
    matchLabels:
      app: specialdays-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: specialdays-service-deployment
    spec:
      containers:
        - name: specialdays-service
          image: gabrielcq/specialdays-service
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SPECIALDAYS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SPECIALDAYS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_SPECIALDAYS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_SPECIALDAYS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_SPECIALDAYS