version: "3.8"
services:
#nginx servers
  nginx-backend:
    image: nginx
    container_name: kartingrm-nginx-backend-container
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - kartingrm-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3
  nginx-frontend:
    image: nginx
    container_name: kartingrm-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - kartingrm-frontend-network
    depends_on:
      - react1
      - react2
      - react3
  postgres:
    container_name: kartingrm-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - kartingrm-postgres-volume:/var/lib/postgresql/data
    networks:
      - kartingrm-backend-network
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5435:5432
 #Backend servers
  spring1:
    container_name: kartingrm-backend-container-1
    image: gabrielcq/kartingrm-backend
    ports:
      - 8091:8090
    environment:
      DB_HOST: kartingrm-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USER_MAIL: fxgatogods@gmail.com
      PASS_EM: bdrunryshbaxqvrv
    networks:
      - kartingrm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: kartingrm-backend-container-2
    image: gabrielcq/kartingrm-backend
    ports:
      - 8092:8090
    environment:
      DB_HOST: kartingrm-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USER_MAIL: fxgatogods
      PASS_EM: bdrunryshbaxqvrv
    networks:
      - kartingrm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: kartingrm-backend-container-3
    image: gabrielcq/kartingrm-backend
    ports:
      - 8093:8090
    environment:
      DB_HOST: kartingrm-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USER_MAIL: fxgatogods
      PASS_EM: bdrunryshbaxqvrv
    networks:
      - kartingrm-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
#frontend servers
  react1:
    container_name: kartingrm-frontend-container-1
    image: gabrielcq/kartingrm-frontend
    ports:
      - 3001:3000
    networks:
      - kartingrm-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: kartingrm-frontend-container-2
    image: gabrielcq/kartingrm-frontend
    ports:
      - 3002:3000
    networks:
      - kartingrm-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: kartingrm-frontend-container-3
    image: gabrielcq/kartingrm-frontend
    ports:
      - 3003:3000
    networks:
      - kartingrm-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  kartingrm-postgres-volume:
networks:
  kartingrm-backend-network:
  kartingrm-frontend-network:
